version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: supertest
    versions:
    - 6.1.3
